# This file generates the GitHub Actions matrix
board: ["nice_nano_v2"]
shield: ["bgkeeb_left", "bgkeeb_right", "settings_reset"]

zmk:
  version: "3.2"
  features:
    - unicode

include:
  - board: nice_nano_v2
    shield: bgkeeb_left
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: bgkeeb_right
  - board: nice_nano_v2
    shield: settings_reset
