manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/ralex2304
    - name: ralex2304
      url-base: https://github.com/ralex2304
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
